name: docker-build
description: Composite action to build images only.

inputs:
  platform:
    description: Target platform.
    required: true
  cache-tag-suffix:
    description: Suffix of the target cache tag.
    required: true
  additional-repos:
    description: Additional target .repos file.
    default: ""
    required: false
  build-args:
    description: Additional build args.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install vcstool
      run: |
        sudo apt-get -y update
        sudo apt-get -y install python3-pip pipx
        pipx install vcstool
      shell: bash

    # NEW (minimal): decide whether to import into "." or "src"
    - name: Detect vcs import root
      id: vcs-root
      run: |
        set -euo pipefail
        # If repos files contain "path: src/...", importing into "src" will create src/src/... (bad).
        if grep -qE '^[[:space:]]*path:[[:space:]]*src/' autoware.repos extra-packages.repos 2>/dev/null; then
          echo "root=." >> "$GITHUB_OUTPUT"
        else
          echo "root=src" >> "$GITHUB_OUTPUT"
        fi
        echo "Using vcs import root: $(cat "$GITHUB_OUTPUT" | sed -n 's/^root=//p')"
      shell: bash

    - name: Run vcs import
      run: |
        mkdir -p src
        vcs import --shallow ${{ steps.vcs-root.outputs.root }} < autoware.repos
        vcs import --shallow ${{ steps.vcs-root.outputs.root }} < extra-packages.repos
      shell: bash

    - name: Import additional repositories
      if: ${{ inputs.additional-repos != '' }}
      run: |
        vcs import --shallow --force ${{ steps.vcs-root.outputs.root }} < ${{ inputs.additional-repos }}
      shell: bash

    - name: Cache ccache
      uses: actions/cache@v4
      if: ${{ github.ref == 'refs/heads/main'}}
      id: cache-ccache
      with:
        path: |
          root-ccache
        key: ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/*.cpp') }}
        restore-keys: |
          ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          ccache-${{ inputs.platform }}-

    - name: Cache apt-get
      uses: actions/cache@v4
      if: ${{ github.ref == 'refs/heads/main'}}
      id: cache-apt-get
      with:
        path: |
          var-cache-apt
        key: apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/package.xml') }}
        restore-keys: |
          apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          apt-get-${{ inputs.platform }}-

    - name: Restore ccache
      uses: actions/cache/restore@v4
      if: ${{ github.ref != 'refs/heads/main'}}
      with:
        path: |
          root-ccache
        key: ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/*.cpp') }}
        restore-keys: |
          ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          ccache-${{ inputs.platform }}-

    - name: Restore apt-get
      uses: actions/cache/restore@v4
      if: ${{ github.ref != 'refs/heads/main'}}
      with:
        path: |
          var-cache-apt
        key: apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/package.xml') }}
        restore-keys: |
          apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          apt-get-${{ inputs.platform }}-

    - name: Inject cache into docker
      # TODO(youtalk): Use the release version again
      uses: reproducible-containers/buildkit-cache-dance@7c892679bab8ff382a8c88ab7f973d5e30a8f239
      with:
        utility-image: ghcr.io/containerd/busybox:latest
        cache-map: |
          {
            "root-ccache": "/root/.ccache",
            "var-cache-apt": "/var/cache/apt"
          }
        skip-extraction: ${{ steps.cache-ccache.outputs.cache-hit && steps.cache-apt-get.outputs.cache-hit }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Run docker build
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        context: .
        push: false
        tags: "local/autoware:${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}"
        load: true
        build-args: ${{ inputs.build-args }}
        cache-from: "type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ inputs.platform }}-main"
