name: docker-build
description: Composite action to build images only.

inputs:
  platform:
    description: Target platform.
    required: true
  cache-tag-suffix:
    description: Suffix of the target cache tag.
    required: true
  additional-repos:
    description: Additional target .repos file.
    default: ""
    required: false
  build-args:
    description: Additional build args.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install vcstool
      run: |
        sudo apt-get -y update
        sudo apt-get -y install python3-pip pipx
        pipx install vcstool
      shell: bash

    # ------------------------------------------------------------
    # REFACTOR: trying 
    # ------------------------------------------------------------
    - name: Prepare workspace
      run: |
        set -eux
        rm -rf __vcs_ws src
        mkdir -p __vcs_ws src
      shell: bash

    - name: Run vcs import into temporary workspace
      run: |
        set -eux
        vcs import --shallow __vcs_ws < autoware.repos
        vcs import --shallow __vcs_ws < extra-packages.repos
      shell: bash

    - name: Import additional repositories (temporary workspace)
      if: ${{ inputs.additional-repos != '' }}
      run: |
        set -eux
        vcs import --shallow --force __vcs_ws < ${{ inputs.additional-repos }}
      shell: bash

    - name: Normalize repository layout to ./src
      run: |
        set -eux

        # Case A: repos already checked out into __vcs_ws/src/...
        if [ -d "__vcs_ws/src" ]; then
          echo "Detected __vcs_ws/src. Moving its contents into ./src"
          # Move contents, not the folder itself
          shopt -s dotglob
          mv __vcs_ws/src/* src/ || true
          shopt -u dotglob

        # Case B: repos checked out directly into __vcs_ws/<something...>
        else
          echo "No __vcs_ws/src. Moving __vcs_ws contents into ./src"
          shopt -s dotglob
          mv __vcs_ws/* src/ || true
          shopt -u dotglob
        fi

        # Remove temp workspace
        rm -rf __vcs_ws

        # Hard validation: these MUST exist for Dockerfile mounts/copies
        test -d src/universe || (echo "ERROR: src/universe not found after normalization" && exit 1)
      shell: bash

    - name: Quick sanity print (paths)
      run: |
        set -eux
        echo "=== top of src ==="
        ls -la src | head -n 100
        echo "=== check expected path(s) ==="
        ls -la src/universe/autoware_universe || true
        ls -la src/universe/autoware_universe/tools || true
        ls -la src/sensor_component || true
      shell: bash

    - name: Cache ccache
      uses: actions/cache@v4
      if: ${{ github.ref == 'refs/heads/main'}}
      id: cache-ccache
      with:
        path: |
          root-ccache
        key: ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/*.cpp') }}
        restore-keys: |
          ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          ccache-${{ inputs.platform }}-

    - name: Cache apt-get
      uses: actions/cache@v4
      if: ${{ github.ref == 'refs/heads/main'}}
      id: cache-apt-get
      with:
        path: |
          var-cache-apt
        key: apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/package.xml') }}
        restore-keys: |
          apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          apt-get-${{ inputs.platform }}-

    - name: Restore ccache
      uses: actions/cache/restore@v4
      if: ${{ github.ref != 'refs/heads/main'}}
      with:
        path: |
          root-ccache
        key: ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/*.cpp') }}
        restore-keys: |
          ccache-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          ccache-${{ inputs.platform }}-

    - name: Restore apt-get
      uses: actions/cache/restore@v4
      if: ${{ github.ref != 'refs/heads/main'}}
      with:
        path: |
          var-cache-apt
        key: apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-${{ hashFiles('src/**/package.xml') }}
        restore-keys: |
          apt-get-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}-
          apt-get-${{ inputs.platform }}-

    - name: Inject cache into docker
      uses: reproducible-containers/buildkit-cache-dance@7c892679bab8ff382a8c88ab7f973d5e30a8f239
      with:
        utility-image: ghcr.io/containerd/busybox:latest
        cache-map: |
          {
            "root-ccache": "/root/.ccache",
            "var-cache-apt": "/var/cache/apt"
          }
        skip-extraction: ${{ steps.cache-ccache.outputs.cache-hit && steps.cache-apt-get.outputs.cache-hit }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Run docker build
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        context: .
        push: false
        tags: "local/autoware:${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}"
        load: true
        build-args: ${{ inputs.build-args }}
        cache-from: "type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ inputs.platform }}-main"
